### ISSUE TITLE
What's the F score means?

### ISSUE THREAD

**Issue by xtmgah** [jmonlong/sQTLseekeR#3]
Hello very good package for sQTL analysis. So, What's the F score means? Is this value can be used as "effect size" ? Thanks.

**Comment by jmonlong** [comment]
The F score is the statistic computed for the test. The higher the value the stronger the effect. We compare this score with permutation or approximation under the null to compute the p-value. 

It's the original statistic but not directly interpretable. The p-value should be used instead.

To filter on the effect size we use the *md* column (maximum difference in relative expression between genotype groups). The package is maintained at [guigolab/sQTLseekeR](https://github.com/guigolab/sQTLseekeR) and you can find a better documentation there, including discussion about the *md* column in the FAQ.

PS: I don't know why there is no "Issues" tab on the new repo. I'll see if we can add it and I would recommend posting questions there.
